pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }

    tools {
        maven 'Maven 3.8.4'
        jdk 'jdk11'
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }
}